#!/usr/bin/env bash
#+    Listens on port 80.
#+    Returns a page containing "Hello world!" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".
# Configures Nginx server with a custom header
sudo apt-get update -y
sudo apt-get install nginx -y
#
# Starting nginx service
sudo service nginx start
#
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
#
# Configure nginx with a custom header
sudo sed -i '24i\        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
#
sudo service nginx restart
